### ISSUE TITLE
Better swapfile size default

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-swapfile#4]
Right now, the static `swapfile_size` default isn't very good. You discussed a better default [here](https://github.com/carlalexander/debops-wordpress/issues/25). Could we change the default to `2 * ansible_memtotal_mb | int` for now?

**Comment by drybjed** [comment]
This should be fixed with https://github.com/debops/ansible-swapfile/pull/5/commits/1317ffc259e566db8e5e499379677ce7b636d219

**Comment by carlalexander** [comment]
Is 512MB enough when you're over 2gigs of RAM? Seems a bit low.

**Comment by drybjed** [comment]
Well, let's see... Up to 2 GB you get twice as that, which would be 6 GB of useable memory with RAM (fast) being 2 GB, and swap (slower) being 4 GB. After 2 GB, which I suspect will be double usually (haven't really seen hosts with 3 GB of RAM), you have 4 GB of fast RAM. At which point swap should only be treated as a small buffer to handle OOM events. If your application needs more than 4 GB of RAM, I think that you would more likely add more RAM than swap anyway.

**Comment by carlalexander** [comment]
Got it! Looks good then!
